### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by caxapexac** [waywardmonkeys/emscripten-trace-collector#5]
Python 3.9.10 without virtualenv

```
pip install -r requirements.txt
Collecting Flask==0.10.1
  Using cached Flask-0.10.1.tar.gz (544 kB)
  Preparing metadata (setup.py) ... done
Collecting Jinja2==2.7.3
  Using cached Jinja2-2.7.3.tar.gz (378 kB)
  Preparing metadata (setup.py) ... done
Collecting MarkupSafe==0.23
  Using cached MarkupSafe-0.23.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting Werkzeug==0.9.6
  Using cached Werkzeug-0.9.6.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
Collecting itsdangerous==0.24
  Using cached itsdangerous-0.24.tar.gz (46 kB)
  Preparing metadata (setup.py) ... done
Collecting pypng==0.0.17
  Using cached pypng-0.0.17.tar.gz (275 kB)
  Preparing metadata (setup.py) ... done
Collecting simplejson==3.6.0
  Using cached simplejson-3.6.0.tar.gz (70 kB)
  Preparing metadata (setup.py) ... done
Collecting wsgiref==0.1.2
  Using cached wsgiref-0.1.2.zip (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\caxap\AppData\Local\Temp\pip-install-6y01n0s5\wsgiref_52659fc8a3724796a7375b21ab0283b9\setup.py", line 5, in <module>
          import ez_setup
        File "C:\Users\caxap\AppData\Local\Temp\pip-install-6y01n0s5\wsgiref_52659fc8a3724796a7375b21ab0283b9\ez_setup\__init__.py", line 170
          print "Setuptools version",version,"or greater has been installed."
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by caxapexac** [comment]
Okay its dead

**Comment by suzukieng** [comment]
@caxapexac stumbled over this as well. You think this project is abandoned in favor of Google WTF?

**Comment by suzukieng** [comment]
Oh wait, Google WTF appears to be dead as well

**Comment by caxapexac** [comment]
@suzukieng yeah no way unfortunately
